version: '3'
services:
  hacker_cookbook:
    build:
      context: ../.admin
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "5000:5000"
    volumes:
            - ../:/app
